// Personal, practical recommendations based on foods already logged.
(function(){
 const n=v=>+v||0;
 const EXCLUDE=/grüner helfer|lavita|vitamin|supplement|kreatin|creatin|öl$|sauce$|dressing$/i;
 function pool(){const map={};Object.entries(allFoods()).forEach(([date,items])=>(items||[]).forEach(x=>{if(!x||!x.name||n(x.g)<=1||EXCLUDE.test(x.name.trim()))return;const z=normalizeItem(x),id=z.name.trim().toLowerCase();if(!z.k)return;if(!map[id])map[id]={...z,count:0,last:'',grams:[]};map[id].count++;map[id].last=date>map[id].last?date:map[id].last;map[id].grams.push(n(x.g));}));return Object.values(map).map(x=>{x.grams.sort((a,b)=>a-b);x.usual=x.grams[Math.floor(x.grams.length/2)]||100;return x;});}
 function remaining(){const t=total();return{k:Math.max(0,GO.k-t.k),p:Math.max(0,GO.p-t.p),c:Math.max(0,GO.c-t.c),f:Math.max(0,GO.f-t.f),b:Math.max(0,GO.b-n(t.b))};}
 function scaled(x,g){const m=g/100;return{name:x.name,g,k:x.k*m,p:x.p*m,c:x.c*m,f:x.f*m,b:x.b*m,s:x.s*m,count:x.count,last:x.last,personal:true};}
 function fits(x,r){return x.k<=r.k+10&&x.c<=r.c+8&&x.f<=r.f+1.5;}
 function score(x,r){const cov=(v,w,wgt)=>w>0?Math.min(v,w)/w*wgt:0;let s=cov(x.p,r.p,48)+cov(x.c,r.c,19)+cov(x.b,r.b,11)+cov(x.k,r.k,10);s-=Math.max(0,x.f-r.f)*15;s-=Math.max(0,x.k-r.k)/Math.max(1,r.k)*120;s+=(x.count||0)*.8;return s;}
 function sensibleGrams(x,r){const usual=Math.max(30,Math.min(400,Math.round(x.usual/5)*5));const maxK=x.k?Math.floor(r.k/x.k*100/5)*5:usual;const maxF=x.f?Math.floor((r.f+1)/x.f*100/5)*5:usual;return Math.max(30,Math.min(usual,maxK,maxF,400));}
 function candidates(){const r=remaining(),items=pool(),singles=[];items.forEach(x=>{const g=sensibleGrams(x,r),q=scaled(x,g);if(g>=30&&fits(q,r))singles.push(q);});const base=singles.sort((a,b)=>score(b,r)-score(a,r)).slice(0,10),combos=[];for(let i=0;i<base.length;i++)for(let j=i+1;j<base.length;j++){const a=base[i],b=base[j];if(a.name===b.name)continue;const q={name:`${Math.round(a.g)} g ${a.name} + ${Math.round(b.g)} g ${b.name}`,g:1,k:a.k+b.k,p:a.p+b.p,c:a.c+b.c,f:a.f+b.f,b:a.b+b.b,s:a.s+b.s,parts:[a,b],count:Math.min(a.count||0,b.count||0),personal:true};if(fits(q,r)&&q.k>=180)combos.push(q);}const all=[...combos,...singles].map(x=>({...x,rank:score(x,r)})).sort((a,b)=>b.rank-a.rank);return all.filter((x,i,a)=>a.findIndex(y=>y.name===x.name)===i).slice(0,5);}
 function label(x){if(x.parts)return x.parts.map(p=>`${Math.round(p.g)} g ${p.name}`).join(' + ');return `${Math.round(x.g)} g ${x.name}`;}
 function reason(x,r){const a=[];if(x.p>=25)a.push(`${Math.round(x.p)} g Eiweiß`);if(r.c>30&&x.c>=20)a.push('liefert Kohlenhydrate');if(r.b>5&&x.b>=4)a.push('liefert Ballaststoffe');if(x.f<=Math.max(8,r.f*.3))a.push('wenig Fett');return a.slice(0,2).join(' · ')||'passt gut in deinen Rest';}
 window.addSmartSuggestion=i=>{const x=(window.smartSuggestions||[])[i];if(!x)return;if(x.parts)x.parts.forEach((p,j)=>foods.push({id:Date.now()+j,name:p.name,g:p.g,k:p.k,p:p.p,c:p.c,f:p.f,b:p.b,s:p.s}));else foods.push({id:Date.now(),name:x.name,g:x.g,k:x.k,p:x.p,c:x.c,f:x.f,b:x.b,s:x.s});save();show('food');};
 window.showHome=function(){updateRemaining();const r=remaining(),list=candidates();window.smartSuggestions=list;let html=`<h3>Was passt jetzt gut?</h3><p class="muted">Dir fehlen heute vor allem ${Math.round(r.p)} g Eiweiß und ${Math.round(r.c)} g Kohlenhydrate. Du hast noch ${Math.round(r.k)} kcal und ${Math.round(r.f)} g Fett frei.</p>`;if(!list.length)html+='<div class="suggestion"><b>Noch nichts Passendes aus deiner bisherigen Lebensmittelliste gefunden.</b><div class="muted">Trage weiter deine normalen Lebensmittel ein. Die Vorschläge lernen daraus.</div></div>';else html+=list.map((x,i)=>`<div class="suggestion"><b>${i===0?'Mein Vorschlag: ':i===1?'Alternative: ':''}${label(x)}</b><div style="margin-top:5px">${Math.round(x.k)} kcal · ${Math.round(x.p)} g Eiweiß · ${Math.round(x.c)} g KH · ${Math.round(x.f)} g Fett</div><div class="muted" style="margin-top:5px">${reason(x,r)} · schon früher von dir eingetragen</div><button class="btn green" style="margin-top:8px" onclick="addSmartSuggestion(${i})">So eintragen</button></div>`).join('');eatList.innerHTML=html;};
})();