// Personal recommendations based on the user's existing bFoods history.
(function(){
 const n=v=>+v||0;
 function pool(){const map={};Object.entries(allFoods()).forEach(([date,items])=>(items||[]).forEach(x=>{if(!x||!x.name||n(x.g)<=1)return;const z=normalizeItem(x),id=z.name.trim().toLowerCase();if(!z.k)return;if(!map[id])map[id]={...z,count:0,last:'',grams:[]};map[id].count++;map[id].last=date>map[id].last?date:map[id].last;map[id].grams.push(n(x.g));}));return Object.values(map).map(x=>{x.grams.sort((a,b)=>a-b);x.usual=x.grams[Math.floor(x.grams.length/2)]||100;return x;});}
 function remaining(){const t=total();return{k:Math.max(0,GO.k-t.k),p:Math.max(0,GO.p-t.p),c:Math.max(0,GO.c-t.c),f:Math.max(0,GO.f-t.f),b:Math.max(0,GO.b-n(t.b))};}
 function scaled(x,g){const m=g/100;return{name:x.name,g,k:x.k*m,p:x.p*m,c:x.c*m,f:x.f*m,b:x.b*m,s:x.s*m,count:x.count,last:x.last,personal:true};}
 function fits(x,r){return x.k<=r.k+10&&x.c<=r.c+5&&x.f<=r.f+1;}
 function score(x,r){let s=0;const cov=(v,want,w)=>want>0?Math.min(v,want)/want*w:0;s+=cov(x.p,r.p,42)+cov(x.c,r.c,20)+cov(x.b,r.b,18)+cov(x.k,r.k,12);s-=Math.max(0,x.f-r.f)*12+s*0;s-=Math.max(0,x.k-r.k)/Math.max(1,r.k)*100;s+=(x.count||0)*1.2;return s;}
 function candidates(){const r=remaining(),out=[];pool().forEach(x=>{const max=Math.max(30,Math.min(500,Math.floor(Math.min(r.k/Math.max(x.k,.01),r.c>0?(r.c+5)/Math.max(x.c,.01):5,r.f>0?(r.f+1)/Math.max(x.f,.01):5)*100/10)*10));const gs=new Set([50,75,100,125,150,200,250,300,Math.round(x.usual/10)*10,max]);gs.forEach(g=>{if(g>=30&&g<=max){const q=scaled(x,g);if(fits(q,r))out.push(q);}});});const base=out.sort((a,b)=>score(b,r)-score(a,r)).slice(0,14),combos=[];for(let i=0;i<base.length;i++)for(let j=i+1;j<base.length;j++){if(base[i].name===base[j].name)continue;const a=base[i],b=base[j],q={name:`${Math.round(a.g)} g ${a.name} + ${Math.round(b.g)} g ${b.name}`,g:1,k:a.k+b.k,p:a.p+b.p,c:a.c+b.c,f:a.f+b.f,b:a.b+b.b,s:a.s+b.s,parts:[a,b],count:(a.count||0)+(b.count||0),personal:true};if(fits(q,r))combos.push(q);}return [...out,...combos].map(x=>({...x,rank:score(x,r)})).sort((a,b)=>b.rank-a.rank).filter((x,i,a)=>a.findIndex(y=>y.name===x.name)===i).slice(0,5);}
 window.addSmartSuggestion=i=>{const x=(window.smartSuggestions||[])[i];if(!x)return;if(x.parts)x.parts.forEach((p,j)=>foods.push({id:Date.now()+j,name:p.name,g:p.g,k:p.k,p:p.p,c:p.c,f:p.f,b:p.b,s:p.s}));else foods.push({id:Date.now(),name:x.name,g:x.g,k:x.k,p:x.p,c:x.c,f:x.f,b:x.b,s:x.s});save();show('food');};
 window.showHome=function(){updateRemaining();const r=remaining(),list=candidates();window.smartSuggestions=list;let html=`<h3>Persönliche Vorschläge</h3><p class="muted">Noch offen: ${Math.round(r.k)} kcal · ${Math.round(r.p)} g Eiweiß · ${Math.round(r.c)} g KH · ${r.f.toFixed(0)} g Fett · ${r.b.toFixed(1)} g Ballaststoffe</p>`;if(!list.length)html+='<div class="suggestion"><b>Noch keine passende Kombination aus deiner Historie.</b><div class="muted">Mit jedem eingetragenen Lebensmittel wird die Auswahl besser.</div></div>';else html+=list.map((x,i)=>`<div class="suggestion"><b>${i===0?'Beste Wahl: ':''}${x.name}</b><div>${Math.round(x.k)} kcal · ${x.p.toFixed(1)} g Eiweiß · ${x.c.toFixed(1)} g KH · ${x.f.toFixed(1)} g Fett · ${x.b.toFixed(1)} g Ballaststoffe</div><div class="muted">Aus Lebensmitteln, die du bereits eingetragen hast${x.count?' · Historie '+x.count+'×':''}</div><button class="btn green" style="margin-top:8px" onclick="addSmartSuggestion(${i})">Eintragen</button></div>`).join('');eatList.innerHTML=html;};
})();